src/components/common/SelectBox.js
src/components/common/selectbox/Box.js
src/components/common/selectbox/DropDown.js
src/hooks/index.js
src/pages/Products/ProductView.js
src/pages/support/board/faq.js

#3 
- 공통 > selectbox
- 기본적인 형태로만 만들었습니다! `dropdown`은 사용하시면서 업데이트 부탁드립니다 🤩🙇‍♂️
- `useToggle`, `useForm` 커스텀 훅을 만들어 두었습니다!
```js
const dummyoptions = [
{
optionNo: 1,
label: 'test',
},
{
optionNo: 2,
label: 'test2',
disabled: true,
},
];
const logSelectedOption = option => console.log(option);
return (
<>
{/* // 박스형태 */}
<SelectBox
selectOptions={dummyoptions}
selectOption={logSelectedOption}
/>
{/* // 드롭다운 형태 */}
<SelectBox
defaultInfo={{
type: 'dropdown',
placeholder: '쿠폰을 선택해주세요.'
}}
selectOptions={dummyoptions}
selectOption={logSelectedOption}
/>
</>
)
```

[공통] selectbox

---

package.json
src/context/board.context.js
yarn.lock

chore: add immer library

---

src/App.js
src/api/admin.js
src/context/mall.context.js
src/provider/GlobalProvider.js

[공통] mall context

---

README.md
published/demo/demo.html
published/html/demo/demo.html
published/html/order/order1.html
published/html/order/order2.html
published/html/order/order3.html
published/order/order1.html
published/order/order2.html
published/order/order3.html
src/components/common/Alert.js
src/components/common/Confirm.js
src/components/common/LayerPopup.js
src/pages/member/joinStep.js
src/pages/member/login.js
src/pages/member/pwSearch.js
src/pages/mypage/myPageMember.js
src/pages/mypage/withdraw.js

샘플 적용 내용은 README에 적어 두었습니다. 
- LayerPopup
- Alert
- Confirm
#3

[공통] 레이어팝업, alert/confirm

---

src/api/order.js
src/pages/Products/ProductView.js
src/pages/order/orderStep1.js

feat: add guest direct order

---

.env.development
.env.production
src/api/admin.js
src/api/auth.js
src/api/display.js
src/api/manage.js
src/api/member.js
src/api/product.js
src/api/request.js
src/api/sony/member.js
src/api/sony/request.js
src/components/EspProduct.js
src/components/Header.js
src/context/global.context.js
src/pages/Products/ProductView.js
src/pages/member/join.js
src/pages/member/joinStep.js
src/pages/member/login.js
src/provider/GlobalProvider.js
src/utils/token.js
src/utils/utils.js

[공통] 토큰 공통 처리

---

src/App.js
src/components/Header.js
src/components/common/Alert.js
src/components/common/Confirm.js
src/components/common/LayerPopup.js
src/pages/member/JoinAgree.js
src/pages/member/joinStep.js
src/pages/member/login.js
src/utils/utils.js

[회원] 회원가입 약관동의

---

src/assets/scss/interaction/accordion.scss
src/components/common/surface/Accordion.js
src/components/order/Products.js
src/pages/order/orderStep1.js

```javascript
import Accordion from '../../components/common/surface/Accordion';
```
``` jsx
<Accordion title={'아코디언 타이틀'}>
아코디언 콘텐츠
</Accordion>
```

[공통][컴포넌트] 아코디언 

---

src/api/product.js
src/pages/Products/ProductView.js
src/pages/Products/productView/RelatedProducts.js
src/pages/Products/utils.js

**제품 상세 > 함께 구매하시면 좋은 추천 제품** 완료

feat: add relatedProducts

---

src/App.js
src/components/Header.js
src/context/profile.context.js
src/pages/member/login.js
src/pages/mypage/myPageMember.js
src/provider/GlobalProvider.js

profile context 생성하였습니다!
@kjkandrea 
@choisohyun

feat: add profile context

---

src/components/Header.js
src/context/profile.context.js
src/pages/mypage/MyPageMember.js

- 회원정보 수정 ui 
- 회원정보 호출 api context 에 추가
- 소니 api 사용하기 때문에 배포 후 이후 로직 추가 필요 (벨리데이션 후 put api 호출)

[마이페이지] 회원정보 수정

---

src/api/manage.js
src/assets/scss/partials/popup/findAddress.scss
src/components/popup/FindAddress.js
src/pages/order/orderStep1.js

* 주소찾기 팝업 레이아웃
* 주소 검색
TODO. 주소 검색 더보기/페이징

[주문] 주문서 작성/결제 > 주소찾기 팝업 : 레이아웃/검색

---

src/App.js
src/context/board.context.js
src/pages/support/board/faq.js
src/pages/support/board/faq/faqContent.js
src/pages/support/board/notice.js
src/pages/support/board/notice/detail.js
src/pages/support/board/notice/noticeContent.js
src/pages/support/board/tabs.js

[고객서비스] FAQ & 공지사항

---

src/App.js
src/api/sony/member.js
src/components/Header.js
src/context/profile.context.js

- Header -> App에서 저장하는 것으로 변경
- shop api의 profile과 sony api 의 my 모두 저장
- sony api는 모두 "post" 
@nanuya 보미님! 회원정보 공통처리 부분 수정하였는데 확인 한 번 부탁드립니다~

[공통] 로그인한 회원정보 공통처리

---

src/api/display.js
src/pages/Products/ProductView.js
src/pages/Products/productView/Event.js

[제품] 상세 > 기획전 

---

src/assets/scss/interaction/field.dynamic.scss
src/components/order/ShippingAddressForm.js
src/components/popup/FindAddress.js

@choisohyun @KwonYG  주소찾기 기능 완성했어요.  선택된 주소 받는건 아래처럼 하실 수 있어요!
``` jsx
import FindAddressPopup from '/components/popup/FindAddress';
const yourComponent = () => {
const [visible, setVisible] = useState(false); // boolean
return (
{ visible && <FindAddressPopup
setVisible={setVisible}
setAddress={address => alert('여기에 선택된 주소 넘어옴 : ', address)}
>}
)
}
```

[주문] 주문서 작성/결제 > 주소찾기 팝업 : 선택된 값 방출

---

published/html/index.html
published/html/membership/membership.html
published/html/membership/membership_vvip.html
src/pages/mypage/MyPageMember.js

[마이페이지] 회원수정 - 우편번호찾기

---

src/components/common/Confirm.js
src/hooks/index.js
src/pages/mypage/MyPageMember.js
src/pages/mypage/myPageMember/Rename.js
src/pages/mypage/myPageMember/Repassword.js

#75 
- 휴대폰 및 아이핀 인증 연결할 가이드 필요

[마이페이지] 회원정보 > 개명회원 본인인증

---

src/pages/member/MobileAuth.js
src/pages/mypage/MyPageMember.js

[마이페이지] 회원정보 > 휴대폰번호 변경을 위한 인증 컴포넌트 개발 완료

[마이페이지] 회원정보 > 휴대폰번호 인증

---

src/assets/images/mypage/ico_mypage_link_4.svg
src/assets/scss/mypage.scss
src/pages/mypage/OldOrderList.js
src/pages/mypage/orderList.js

[주문/배송 내역] 이전주문내역 라우트, 애셋 추가

---

src/components/Gnb.js
src/components/Header.js
src/context/header.context.js
src/provider/GlobalProvider.js

- header 컨텍스트 추가 
- 메뉴별 close 추가

[헤더] 메뉴 클릭 후 사이드바 안닫히는 문제 수정

---

src/pages/mypage/MyPageMember.js
src/pages/mypage/myPageMember/Repassword.js

[마이페이지] 회원정보 비밀번호변경 버그 수정

---

package.json
src/assets/scss/partials/datePicker.scss
src/components/common/DatePicker.js
src/components/order/ShippingAddressForm.js
src/utils/dateFormat.js

``` jsx
import DatePicker from '/components/common/DatePicker';
const yourComponent = () => {
return (
<DatePicker
bindDate={stringDateFormat => alert(stringDateFormat)} // 여기에 선택된 일자 string 으로 넘어옴
option={{
selectableRanges: [[new Date(), new Date(2999, 12, 31)]], // range 설정
}}
/>
)
}
```

[공통] Date Picker 추가

---

src/components/common/DatePicker.js
src/components/order/ShippingAddressForm.js

[주문] 주문서 작성/결제 > 배송일자 선택 : 비즈니스 로직

---

src/api/sony/order.js
src/components/order/OrderListItem.js
src/pages/mypage/orderList.js

- 주문 목록 출력
- 주문목록 아이템 컴포넌트
- 상태별 버튼 출력
- 환불계좌정보
- 주문취소
- 배송조회

[주문/배송 내역] 주문목록 출력, 상태별 버튼 출력

---

src/components/order/OrderListItem.js
src/pages/mypage/orderDetail.js

[주문/배송 내역] 주문 상세 마크업, 라우트

---

src/components/common/LayerPopup.js
src/pages/mypage/Withdraw.js

[회원] 회원탈퇴 - Fix withdraw click event

---

src/assets/scss/common.scss
src/assets/scss/mypage.scss
src/components/Header.js
src/pages/mypage/MyPageMember.js

- a 태그 -> Link 로 수정
- 서브메뉴 접기 버그 수정
- 회원수정 후 새로운 회원정보로 업데이트 로직 추가

[공통] 헤더 (링크 및 서브메뉴 접기)

---

src/pages/member/joinStep.js

[회원] 회원가입 후 로그인 기능

---

src/api/order.js
src/components/order/OldOrderListItem.js
src/components/order/OrderListItem.js
src/pages/mypage/OldOrderList.js
src/pages/mypage/orderDetail.js
src/pages/mypage/orderList.js

- 이전 주문 목록
- 소니 API 연결
- 이전 주문 목록 아이템

[주문/배송내역] 이전주문목록 

---

src/api/order.js
src/hooks/index.js
src/pages/mypage/orderDetail.js

- 주문 상세 내역 API 추가
- useQuery 훅 추가

[주문/배송 내역] 주문 상세 내역 API 추가, useQuery

---

public/index.html
src/components/order/Calculator.js
src/components/order/DiscountForm.js
src/components/order/PaymentForm.js
src/components/order/ShippingAddressForm.js
src/components/order/orderPayment.js
src/components/popup/UseCoupon.js
src/const/paymentType.js
src/module/payment.js
src/pages/order/orderStep1.js
src/utils/unit.js

**현재 KCP 결제 모듈 뜹니다. (이니시스로 변경 필요)**
@KwonYG 
현재 주문서 구현 덜되었고 아래와 같은 방식으로 payment reserve 가능합니다.
1. 상품 상세 => 바로구매 하기로 주문서 진입. 
2. [필드 자동입력] 버튼 동작
3. [결제하기] 버튼 동작

[주문] 주문서 작성/결제 : 결제모듈 연동 및 필드 자동채움 기능(테스트용)

---

src/assets/scss/membership.scss
src/components/common/Tabs.js
src/pages/Products/productView/BottomContent.js
src/pages/membership/Benefit.js

[멤버쉽] 등급&혜택 안내

---

src/App.js
src/components/Gnb.js
src/const/category.js
src/context/category.context.js
src/provider/GlobalProvider.js

* 카테고리 하드코딩 데이터 추가
* 카테고리 데이터 init 로직 추가
* GNB 카테고리 하드코딩 데이터 별도 분리 (스토어 추천 제품, 제품, 기획전, 멤버십, 고객 서비스)
* GNB 코드 정리
close #113

Feature/#80 -> develop

---

src/components/order/OrderDetailProductItem.js
src/components/order/OrderProcess.js
src/pages/mypage/orderDetail.js

- 주문상태
- 주문 상태별 그래프 UI
- 결제정보
- 신용카드 대응
- 가상계좌 대응
- 결제금액정보
-  할인금액 필드 매핑 확인 필요

[주문상세]  주문상태, 결제정보, 결제금액정보

---

src/pages/membership/Benefit.js

fix: image path error

---

src/components/common/DatePicker.js
src/components/order/DateBox.js
src/pages/mypage/OldOrderList.js

- input 높이 조정가능하도록 height 프롭 추가
- 부모에서 date 값 관리하도록, dateValue 프롭 추가
@kjkandrea DatePicker 약간 수정 들어갔는데 확인 부탁드립니다.

[공통] 기간별 선택 DatePicker

---

src/components/common/LayerPopup.js
src/components/order/OrderListItem.js
src/components/order/OrderProcess.js
src/pages/mypage/orderDetail.js
src/pages/mypage/orderList.js
src/pages/order/RefundAccount.js

- 환불계좌정보팝업
- 상품준비중 -> 배송준비중으로 변경

[주문/배송 내역] 환불계좌정보팝업, 상품준비중 -> 배송준비중으로 변경

---

src/App.js
src/api/display.js
src/components/event/Bottom.js
src/components/event/Top.js
src/pages/event/BenefitZone.js
src/pages/event/EventDetail.js
src/pages/event/Expired.js
src/pages/event/Only.js
src/pages/event/PreOrder.js
src/pages/event/eventList.js

-  배너 슬라이드 api 연결
-  기획전 리스트 api 연결
-  탭 이벤트 연결
-  최신순/마감순 정렬 기능

기획전 - 공통 배너 & 탭 리스트 

---

src/api/sony/order.js
src/components/order/DateBox.js
src/pages/mypage/OldOrderList.js

[주문/배송 내역] 더보기, 기간별 검색 

---

src/pages/mypage/OldOrderList.js

[주문/배송 내력] 이전주문내역

---

src/pages/mypage/OldOrderList.js

[이전주문내역] loadMore 버그 fix

---

src/components/order/GuestPasswordForm.js
src/pages/order/orderStep1.js

[주문] 주문서 작성 > 비회원 비밀번호

---

src/components/Header.js
src/components/order/DateBox.js
src/pages/mypage/OldOrderList.js
src/pages/mypage/orderList.js

- 기간검색, 더보기, 비회원 로그인 라우트, 공지변경

[주문/배송내역] 기간검색, 더보기, 비회원 로그인 라우트, 공지변경

---

src/components/order/GuestPasswordForm.js
src/components/order/OrdererForm.js
src/components/order/PaymentForm.js
src/components/order/ShippingAddressForm.js
src/context/guest.context.js
src/pages/order/orderStep1.js

[주문] 주문 : 폼 벨리데이션

---

src/pages/mypage/OldOrderList.js
src/pages/mypage/orderList.js

- 주문내역, 이전주문내역 나음 페이지 데이터 없을 때 더보기 버튼 삭제
- 검색 search 함수로 통일

[주문/배송내역] 주문내역, 이전주문내역 더보기 

---

src/components/order/DiscountForm.js
src/components/order/ShippingAddressForm.js
src/components/popup/PickRecentAddresses.js
src/components/popup/UseCoupon.js
src/context/guest.context.js
src/pages/order/orderStep1.js

[주문] 주문 > 회원 주문시 주소 관련

---

package.json
src/components/products/ProductList.js
src/const/category.js
yarn.lock

* add react-infinite-scroll-component module

Add infinite scroll in category (#80) -> develop

---

src/api/sony/order.js
src/assets/scss/partials/popup/invoice.scss
src/components/order/PaymentForm.js
src/components/popup/InvoiceGuide.js
src/components/popup/InvoicePublish.js
src/pages/order/orderStep1.js

* 세금계산서 안내
* 세금계산서 신청
* 세금계산서 신청 후 확인
고객사 API여서 배포후 테스트 필요

[주문] 주문 > 가상계좌 선택 > 세금계산서 

---

src/api/claim.js
src/components/myPage/order/OrderListItem.js
src/pages/mypage/orderList.js
src/pages/order/RefundAccount.js

[주문/배송내역] 환불계좌정보, 입력

---

src/App.js
src/api/display.js
src/assets/scss/contents.scss
src/components/Search.js
src/components/common/ViewMore.js
src/components/search/CategoryResult.js
src/components/search/EventResult.js
src/components/search/NoticeResult.js
src/components/search/ProductResult.js
src/components/search/ResultTop.js
src/components/search/Tab.js
src/const/search.js
src/pages/footer/searchResult.js
src/utils/dateFormat.js

#23 
- 상품, 카테고리, 이벤트, 공지 검색 결과 컴포넌트 추가
- TODO
- 더보기
- 정렬

[공통] 검색 > 상세 컴포넌트 추가

---

src/App.js
src/api/order.js
src/components/order/ShippingAddressForm.js
src/pages/order/giftReceive.js
src/pages/order/orderSheet.js

[주문] 선물하기 > 선물 받는사람 배송지 입력

---

src/api/order.js
src/components/myPage/order/OrderProcess.js
src/pages/member/login.js
src/pages/mypage/orderDetail.js

[주문 상세 조회] 비회원 주문 상세 조회

---

src/components/order/Calculator.js
src/components/order/DiscountForm.js

마일리지는 shop mileage 가 아닌 sony mileage 사용

[주문] 샵 마일리지 => 소니 마일리지로 변경

---

src/components/products/ViewTopContent.js

#16 
[제품] 상세 > 선물하기 및 바로구매 로직 추가

[제품] 상세 > 선물하기 및 바로구매 로직 추가

---

src/components/products/ViewTopContent.js

[제품] 상세 > 선물하기

---

src/App.js
src/api/order.js
src/components/cart/Empty.js
src/components/cart/Header.js
src/components/cart/ProductList.js
src/components/cart/QnA.js
src/pages/order/Cart.js
src/pages/order/cart.js
src/storage/guestCart.js
src/utils/storage.js

@nanuya @crazydj2 
비회원의 경우 상품 상세, 상품 리스트에서 장바구니 담아주실때 아래처럼 담아주세요.
``` javascript
// module
import gc from '/storage/guestCart.js';
gc.set(product) // product 에 상품 데이터 담아주세요.  (shopby skin 참고)
```

[주문] 장바구니 > 빈 카트 & 비회원 카트 스토리지

---

src/components/support/LoadedNaverMap.js
src/components/support/StoreGuide.js
src/const/support.js
src/pages/support/storeInfo.js

close #19 
- 직영점 코드 정리
- swiper 추가
- as 센터 찾기 추가

[고객 서비스] 직영점 안내 완료

---

src/components/Header.js
src/components/event/Bottom.js
src/context/category.context.js
src/utils/utils.js

[기획전] gnb, 기획전 탭 회원 설정에 따라 구분

---

src/api/order.js
src/components/common/ViewMore.js
src/components/products/Notification.js
src/components/products/ViewTopContent.js
src/const/productView.js

#16 
[제품] 상세 > 장바구니
- 팝업 및 장바구니 추가 로직

[제품] 상세 > 장바구니

---

src/App.js
src/components/event/Bottom.js
src/pages/event/employee.js
src/pages/event/liveon.js
src/pages/event/refined.js
src/pages/event/refurbish.js

- 별도몰의 주소에도 eventNo 값이 붙도록 변경 
- 리퍼비시볼 완료

[기획전] 리퍼비시몰, 기획전 주소 변경

---

src/components/event/Bottom.js
src/components/event/EventProducts.js

바로 구매하기 클릭 시 첫번째 옵션으로 카트에 넣고 카트로 이동하기
기획전 끝!

[기획전] 바로 구매하기 기능

---

src/api/order.js
src/components/myPage/order/OrderListItem.js
src/components/myPage/order/OrderStatusSummary.js
src/pages/mypage/orderDetail.js
src/pages/mypage/orderList.js

[주문상세, 주문/배송내역] 배송요청일, 선물하기, 클레임 대응

---

src/api/request.js
src/pages/products/ProductView.js

[공통] path variable error 처리 추가

---

src/App.js
src/assets/scss/mypage.scss
src/components/Header.js
src/components/common/LayerPopup.js
src/pages/mypage/Withdraw.js

[회원] Unit test

---

src/api/product.js
src/components/products/CategoryHeader.js
src/components/products/Product.js
src/components/products/ProductList.js

* 컬러칩 로직 및 화면 개발
프리미엄 어드민 추가 개발 완료 후 마무리 예정

[제품] 카테고리 리스트 개발 (#80 -> develop)

---

src/components/common/SelectBox.js
src/components/common/selectbox/Dropdown.js
src/components/event/Bottom.js
src/components/event/EventProducts.js
src/pages/event/Expired.js
src/pages/event/liveon.js
src/utils/utils.js

[기획전] 종료된 기획전

---

src/api/display.js
src/components/event/EventProducts.js
src/pages/event/Expired.js
src/pages/event/liveon.js
src/pages/mypage/Withdraw.js
yarn.lock

- 새로 생성된 API 연결
- 필요없는부분 삭제처리
- 탈퇴시 status 알럿 조건 수정
- 이벤트 상세 하단에 목록 버튼 추가

[기획전] 종료된 기획전 - api 연결 외

---

src/components/cart/Empty.js
src/components/cart/tableParticals/ProductList.js
src/components/popup/Solicitation.js
src/pages/order/Cart.js

* 회원 구매 페이지로 push
* 비회원 구매 페이지로 push
TODO. 장바구니내에 견적서 구현

[주문] 장바구니 > 구매

---

src/assets/scss/contents.scss

[회원가입] mobile radio 스타일 적용

---

src/api/display.js
src/pages/event/Expired.js

[기획전] 종료된 기획전 - 검색, 더보기 기능 

---

src/components/myPage/order/OrderListItem.js
src/pages/mypage/orderDetail.js
src/pages/order/RefundAccount.js

[주문상세, 주문목록] 취소 로직 수정

---

src/api/product.js
src/components/common/selectbox/Box.js
src/components/products/MainImage.js
src/components/products/RelatedProducts.js
src/components/products/ViewBottomContent.js
src/components/products/ViewTopContent.js
src/pages/products/ProductView.js
src/utils/product.js

- 컬러칩 완료
- 옵션 컬러 값 추가
- 메인이미지 1개인 경우 navigation 숨김처리
(컴포넌트에 1개의 데이터가 들어가더라도 swiper 자체에서 반복시켜 노출함
-> 임시로 숨김처리 해두었는데 다수의 이미지가 있을 경우에 문제 발생할 수 있어 메모)
- BottomContent 에서 pc / mo 스타일 구분 때문에 스크립트 추가하는 요청 처리
```js
const windowWidth = window.innerWidth;
const mobileWidth = 640;
const regImg = document.querySelectorAll(".detail_info .regImg");
if (windowWidth <= mobileWidth) {
regImg.forEach(elem => {
let imgsrc = elem.getAttribute("src");
imgsrc = imgsrc.replace(/pc_/g, "mo_");
elem.setAttribute("src", imgsrc)
})
} 
```

[제품] 상세 > 컬러칩 & 상세보기 영역

---

src/components/event/Bottom.js
src/components/popup/Share.js
src/components/products/ViewTopContent.js
src/const/share.js
src/utils/share.js

@choisohyun `event > Bottom` 에 있는 `sns 공유` 참고하면서
- shareKakaoButton, shareKakaoStoryButton 유틸로 빼두었습니다~!
감사합니다!

[제품] 상세 > 공유하기

---

src/api/product.js
src/components/products/ViewTopContent.js
src/const/productView.js
src/pages/products/ProductView.js

[제품] 상세 > 찜하기

---

src/api/product.js
src/assets/css/contents.css
src/components/Search.js
src/components/products/RelatedProducts.js
src/components/search/CategoryResult.js
src/components/search/EventResult.js
src/components/search/Newest.js
src/components/search/NoticeResult.js
src/components/search/ProductResult.js
src/components/search/ResultTop.js
src/components/search/Tab.js
src/const/search.js
src/pages/footer/SearchResult.js
src/pages/footer/SearchResultNone.js

close #23 
- `인기검색어` 기능 추가
- `추천상품` 추가
- 현재는 `MD 추천순`으로 되어 있음. 
- `카테고리 더보기` 기능 추가
-  `최신순/오래된순` 공통 컴포넌트 추가
- `이벤트 더보기` 기능 추가
- `상품검색 결과 더보기` 기능 추가
- `검색결과 없음` 추가

[공통] 검색 완료

---

src/api/promotion.js
src/components/myPage/main/CouponList.js
src/components/myPage/main/OrderSummary.js

[마이페이지] 초기화면 > 쿠폰내역(coupon api 추가)

---

published/css/product.css
src/assets/css/contents.css
src/assets/scss/common.css
src/assets/scss/common.scss
src/assets/scss/product.scss
src/components/common/selectbox/Box.js
src/components/products/Product.js
src/components/products/ProductList.js
src/components/products/RelatedProducts.js
src/components/products/ViewTopContent.js
src/components/products/viewTopContent/Option.js
src/pages/footer/SearchResult.js
src/pages/footer/SearchResultNone.js
src/utils/product.js

- contents.css 임포트 이슈
- 상품코드 isSoldOut 필드 추가
- 검색 버그 수정
- 상품 금액 할인 적용

feat: complete product-view

---

src/api/sony/mileage.js
src/components/myPage/main/MemberSummary.js
src/components/myPage/main/MlieageList.js
src/pages/mypage/MyPageMain.js

[마이페이지] 메인 > 마일리지

---

src/components/products/viewTopContent/ButtonGroup.js
src/pages/products/ProductView.js

[제품] 상세 장바구니 버그 수정

---

src/api/promotion.js
src/components/myPage/main/CouponList.js
src/components/myPage/main/CouponListItem.js

- 쿠폰리스트
- 쿠폰 출력
- 더보기
@kjkandrea 오? 스타일 고쳐주셨네요.   쿠폰쪽 완료하였습니다.

[마이페이지] 초기화면 > 쿠폰리스트

---

src/components/products/ViewTopContent.js
src/components/products/viewTopContent/Benefits.js

[제품] 상세 > 마일리지 부분 주석처리
#16 
추후 사용시
`src/components/products/ViewTopContent.js` 에서 `Benefits`부분만 주석 풀어주시면 됩니다.
```js
{/* 마일리지 부분 주석처리 */}
{/* <Benefits
price={price}
/> */}
```

[제품] 상세 > 마일리지 부분 주석처리

---

src/components/myPage/DateBox.js
src/components/myPage/main/CouponList.js
src/components/myPage/order/OrderListItem.js
src/pages/mypage/orderDetail.js
src/pages/order/RefundAccount.js

- openAlert 콜백 수정
- class -> className @kjkandrea

[마이페이지] 주문내역 > 환불계좌입력

---

src/pages/mypage/orderDetail.js
src/pages/mypage/orderList.js
src/pages/order/RefundAccount.js

[마이페이지] 환불계좌입력 (onlyNumber, 스타일수정, 비회원 주문취소)

---

src/components/myPage/orderDetail/OrderSummary.js
src/pages/mypage/orderDetail.js

- 취소(0원환불) ui 텍스트 대응
- defaultClaimStatus

[마이페이지] 주문상세 (취소(0원환불), defaultClaimStatus)

---

src/pages/member/Search.js
src/pages/member/joinStep.js
src/pages/member/login.js

-  [아이디/비번찾기] 인풋박스 값 미입력 후 [확인] 클릭 시 안내문구 출력 되지 않음.
-  [비회원로그인] 주문번호/비밀번호 항목 미입력 시 안내문구 출력 되지 않음
-  [회원가입] 회원 이름 항목에 허용되지 않은 문자가 입력 됨.

[내부 QA] 로그인, 회원가입

---

src/components/search/CategoryResult.js
src/const/category.js

[검색] 카테고리 next url 추가
참고사항:
`src/const/category.js` 의 `categoriesExtraDataMap` 를 사용하여 `next url` 을 얻음

[검색] 카테고리 next url 추가

---

src/pages/products/ProductView.js

[제품] 상세보기 첫번째 이미지 버그 수정

---

src/assets/scss/common.css
src/components/common/selectbox/Box.js
src/components/products/ViewTopContent.js
src/components/products/viewTopContent/Option.js
src/components/products/viewTopContent/SnsShare.js
src/utils/product.js

상품명과 영문상품명이 거꾸로 되어있었음 -> 수정 완료
옵션 선택 시 컬러가 선택된 창에 노출되지 않는 이슈 해결

[제품] 상품명 및 옵션 선택 시 컬러칩 로직 수정

---

src/assets/scss/partials/myPageBanner.scss
src/components/myPage/main/BToBBanners.js

@Elllin 
배너 컴포넌트 구현만 해두었고 마크업 & 기획서 참고하여 실데이터를 넣어주어야합니다.
현재 `bannerCode: 018`번 배너에 실데이터를 넣어주면 정상 렌더링되나 어드민에 실데이터 넣어주면서 몇가지 마무리작업을 해주어야할것같습니다.

[마이페이지] 메인 > 프로모션 배너 : 배너 데이터 연동 (sample)

---

src/assets/scss/partials/popup/findAddress.scss

close #262 
@kjkandrea 대리님 `findAddress.scss` 에서 `.page` 관련 스타일을 `.find_address` 하위로 옮겼습니다.
확인 하였는데 아래와 같이 이상 없는 것으로 확인되어 노티만 남기고 바로 머지하겠습니다~!

[소니QA] 공통 - 개인정보처리방침, 이용약관

---

src/components/Gnb.js
src/pages/footer/SiteMap.js

[소니QA] 고객서비스

---

src/api/request.js
src/components/common/Alert.js
src/components/products/ViewTopContent.js
src/components/products/viewTopContent/ButtonGroup.js
src/pages/member/login.js
src/pages/products/ProductView.js

[제품] 구매하기 버그 수정

---

src/components/products/viewTopContent/ButtonGroup.js
src/pages/member/login.js

fix next Uri

---

src/pages/support/videoCourse.js

fix: video course TB/MO

---

src/components/cart/CartCount.js
src/pages/member/joinStep.js
src/pages/mypage/Withdraw.js

- 회원가입& 로그인후 헤더 이름정보
-  회원탈퇴 api call flow 오류
- 로그아웃시 cart api 호출하지 않도록 수정

[소니 QA] 로그인, 회원가입, 회원탈퇴

---

src/components/products/Banner.js
src/const/category.js

Fix 대카테고리 내 배너 로직 수정 (#80 -> develop)

---

src/components/Header.js
src/components/event/Bottom.js
src/pages/member/joinStep.js
src/pages/mypage/Withdraw.js

-  [기획전] 임직원이 아닌 경우, 임직원몰 탭 미노출 되도록 처리
-  [기획전] 하위 메뉴 탭 이동 시, 이전에 선택 된 정렬기준이 적용 되어있음.
-  로그인후 헤더 이름정보
- 회원탈퇴 api call flow 오류

[QA] 기획전, 회원탈퇴, 로그인 

---

src/assets/scss/partials/popup/repassword.scss
src/pages/mypage/myPageMember/Repassword.js

fix: repassword error

---

src/components/common/Confirm.js
src/components/common/Floating.js

[공통] 플로팅 #292

---

src/components/products/Product.js
src/components/products/ViewTopContent.js
src/components/products/viewTopContent/Option.js
src/components/products/viewTopContent/SnsShare.js

fix productName

---

src/api/sony/coupon.js
src/components/myPage/main/CouponList.js

@kjkandrea 쿠폰 동기화 API 추가 및 호출 코드 추가했습니다~

feat: add sync coupon api and call

---

src/pages/mypage/MyPageMain.js

fix: change tab to whole page

---

src/components/Footer.js
src/const/footer.js

feat: add sony-family

---

src/components/order/GuestPasswordForm.js

[QA] 비회원  주문의 비밀번호 컬럼타입 변경

---

src/pages/membership/Benefit.js

update premium service text

---

src/pages/support/board/notice/NoticeItem.js

fix: notice index

---

src/components/cart/tableParticals/Controller.js

카트 선택삭제 체크 버그

---

src/pages/order/Cart.js

fix: cart orderCnt sum

---

src/components/cart/tableParticals/ProductList.js

fix: remove option title ui

---

src/components/myPage/main/WishList.js
src/pages/mypage/MyPageMain.js

[QA] 찜한상품 더보기 & 상품상세 링크연결

---

src/api/sony/order.js
src/components/cart/HsValidationMiddleware.js
src/components/cart/HsValidator.js
src/components/products/ViewTopContent.js
src/components/products/viewTopContent/ButtonGroup.js

@nanuya 
상품상세 파악 및 대응이 좀 더 필요할것같아 구두상으로 말씀주신것처럼 아직 머지하지 않겠습니다.
일단 `<HsValidator />` 라는 이름의 `이 상품을 카트에 담을 수 있을지, 없을지` 판별하는 컴포넌트를 구현해놓았어요.
``` jsx
const hsValidator = createRef();
const hsValidation = hasHsCode => hsValidator.current.validation(hasHsCode);
function foo() {
const valid= hsValidation(hasHsCode) 
// @hasHsCode : 장바구니 담을때 (담는상품이 hsCode가 있는상품인지, 아닌지) 넘기면 boolean 리턴
// @valid : valid 가 true 면 담기가능. false 면 <HsValidator /> 가 얼럿 메시지 출력함
}
return (
<HsValidator ref={hsValidator} />
)
```
확인 필요한 부분 : 
* hsValidation(hasHsCode) 시 상품상세 응답값이 hsCode 가 있으면 하위 옵션 상품들도 모두 맴버쉽상품 이라고 판단하여도 되는지
* 비회원 구매시 hsCode 정보가 있는 장바구니 담기 데이터를 어떻게 만들어야하는지
화요일날 확인 필요할듯합니다. 일단 머지하지 않겠습니다.

[상품] 상품상세 > 일반상품은 맴버쉽상품(hsCode: 'foo') 과 함께 장바구니에 담을 수 없다.

---

src/assets/css/common.css
src/assets/scss/common.css
src/assets/scss/common.scss
src/assets/scss/mypage.scss
src/components/myPage/main/CouponListItem.js

- 스타일 최신버전으로 업데이트
- common.css, common.scss, mypage.scss
- 마이페이지 쿠폰 스타일 변경

update: my-page coupon-list style

---

src/components/products/MainImage.js
src/components/products/ViewTopContent.js
src/pages/products/ProductView.js

[QA] 제품상세 메인이미지

---

src/components/common/DatePicker.js
src/components/myPage/DateBox.js

[QA] DateBox(DateRangePicker) 모바일 대응

---

src/components/Footer.js

Fix Foooter console alert (#360 -> develop)

---

src/components/products/viewTopContent/ButtonGroup.js

fix mapping product number

---

src/components/Gnb.js
src/utils/detectAgent.js

앱 디텍터 테스트 코드 적용

---

src/components/common/DatePicker.js
src/components/myPage/DateBox.js
src/components/myPage/main/MlieageList.js

[QA] DateBox 오른쪽 인풋 캘린더 position 수정

---

src/components/Gnb.js
src/utils/detectAgent.js

Add agent/scheme test

---

src/assets/css/mypage.css
src/components/myPage/main/CouponList.js

@nanuya 쿠폰리스트 div에 padding이랑 라인 들어가는거 지웠습니다.

[QA] 마이페이지 > 쿠폰 스타일 깨짐 수정

---

src/assets/scss/contents.scss
src/assets/scss/event.scss
src/components/event/Bottom.js
src/pages/event/eventList.js

[기획전] 종료된 기획전 퍼블리싱 이슈

---

src/components/myPage/order/OrderListItem.js

[QA] 주문/배송리스트 > 주문상품, 옵션 제거

---

src/components/myPage/orderDetail/OrderDetailProductItem.js

[QA] 주문 상세 > 옵션 타이틀 제거

---

src/assets/scss/product.scss
src/pages/products/ProductView.js

fix product-view tab size

---

src/components/order/Products.js

[QA] 주문/결제 페이지 > 옵션삭제

---

src/api/request.js
src/components/myPage/order/OrderListLinkBox.js
src/pages/mypage/orderList.js

[QA] 마이페이지 > 시스템얼럿

---

src/App.js
src/components/event/GradeSelect.js
src/pages/event/asc.js
src/pages/event/employee.js
src/pages/event/refurbish.js

[기획전] asc몰

---

src/components/common/Floating.js

- 전달받은 가이드대로 수정
- 확인이 필요한 부분: 해당 카카오상담으로 연동 시 "한국클라우드_test11"로 연결됨
- 확인 요청한 상태임. 회신 오면 확인 후 머지하기

[공통] 카카오상담 업데이트

---

src/api/request.js
src/components/myPage/order/OrderListItem.js

[QA] 가상계죄 > 환불계좌 취소

---

src/components/products/ProductList.js
src/pages/footer/SearchResult.js

#397 
- 카테고리 목록 및 상품검색 결과 리스트에서 등급상품 제외 처리

fix hsCode products for Category and SearchResult

---

src/components/Search.js

update recommended products

---

src/assets/scss/product.scss
src/components/products/Notification.js
src/components/products/viewTopContent/ButtonGroup.js
src/const/productView.js

[QA] 비회원 구매 동의 팝업

---

src/pages/member/MobileAuth.js
src/pages/mypage/MyPageMember.js

- 이름 변경하기 인증절차에 대한 기획이 없어 모바일변경 시 휴대폰 인증으로 동일하게 처리
- 이름은 최종 회원정보가 완료되어야 변경 됨
- TODO
- auth type code 확인필요

[QA] 회원정보 > 이름 변경

---

src/pages/app/PushList.js

[앱] 푸쉬알림 메시지함 - 데이터 세팅

---

src/assets/scss/mypage.scss

[QA] 마이페이지 > 배너 깨짐

---

src/components/Search.js

[공통] 인기검색어

---

src/components/myPage/main/CouponList.js
src/components/myPage/main/OrderSummary.js
src/components/myPage/order/OrderStatusSummary.js
src/pages/mypage/orderList.js

[QA] 주문/배송내역 > 교환 반품

---

src/App.js
src/pages/app/Landing.js

https://devstore.sony.co.kr/handler/mobile/Common-PageView?pageName=jsp/mobile/common/emptyPage.jsp 
를 대체하는 앱 초기진입 페이지

[앱] 랜딩페이지 (빈페이지)

---

src/components/common/SelectBox.js

[QA] 공통 > SelectBox

---

src/components/myPage/order/OrderListItem.js
src/components/myPage/orderDetail/OrderSummary.js
src/pages/mypage/orderDetail.js
src/pages/mypage/orderList.js

[QA 주문/배송내역 > 반품처리 배송중탭에 출력

---

src/components/Search.js

[QA] 검색바 추천제품과 결과없음 추천제품

---

src/components/Search.js
src/pages/mypage/MyPageMain.js
src/pages/mypage/MyPageMember.js
src/pages/mypage/OldOrderList.js
src/pages/mypage/Withdraw.js
src/pages/mypage/WithdrawComplete.js
src/pages/mypage/orderList.js
src/pages/order/OrderSheet.js
src/pages/products/ProductView.js

[QA] 옴니추어 추가 적용

---

src/pages/order/Cart.js

[QA] 장바구니 > 전체선택 default

---

src/components/order/DiscountForm.js

Add minPriceLimitUnder

---

src/components/order/PaymentForm.js

[QA] 전자 세금서 오타 fix

---

src/api/request.js

cart/count에서 간헐적으로 에러발생하지 않아야하는부분에 에러알럿떠서 수정함

[QA] 401 에러 공통처리 수정 - cart/count

---

src/components/event/Bottom.js

[QA] 기획전 > LIVE ON 

---

src/components/myPage/order/OrderListLinkBox.js
src/pages/mypage/OldOrderList.js

[QA] 이전 주문 내역 > 월 변경

---

src/components/order/OrdererForm.js
src/components/order/ShippingAddressForm.js
src/pages/order/OrderSheet.js

[QA] 주문/결제(비회원) - 정보입력

---

src/assets/scss/contents.scss

[QA] 주문/상세 > 썸네일 이미지

---

src/components/member/OpenLogin.js

[QA] 간편로그인 - 로그인 성공 후 로직 수정

---

src/pages/mypage/Withdraw.js

회원탈퇴시 까만화면 -> 탈퇴성공후 참조할memberId가 없어서 에러발생

[QA] 회원 (회원탈퇴)

---

src/assets/scss/partials/orderBreadcrum.scss

[QA] 주문/결제 -> 숫자라인, 팝업 내 스크롤

---

src/hooks/support.js

[QA] 푸터 > 이용약관

---

src/components/products/viewTopContent/ButtonGroup.js
src/components/products/viewTopContent/Option.js
src/pages/products/ProductView.js

[QA] 제품상세 스타일 조정

---

src/components/Footer.js

[QA] 공통 > 패밀리사이트

---

src/components/popup/InvoiceGuide.js

[QA] 비회원주문 > 모바일 

---

src/components/Gnb.js
src/components/Header.js

[QA] 모바일 gnb

---

src/components/products/Event.js

[QA] 제품상세 > 기획전 노출

---

src/components/order/DiscountForm.js

[QA] 주문/결제 > 마일리지

---

src/components/products/ViewTopContent.js
src/components/products/viewTopContent/Option.js
src/pages/products/ProductView.js

상품 그룹코드로 묶인 상품의 판매상태 업데이트
close #718

[QA] 제품상세 > 재고 (상품 그룹코드 - 판매상태)

---

src/components/products/viewTopContent/Option.js
src/pages/products/ProductView.js

[제품] 상세 > 대표상품 기준 정렬

---

src/components/order/DiscountForm.js

[QA] 주문/결제 > 마일리지 기획변경

---

src/App.js
src/components/common/customPopup/CustomPopup.js
src/components/common/customPopup/partials/validPageDisplayOption.js

디자인팝업관련 개발덜된 브랜치이나 pageTypes 란 값이 response 에서 없어지면서 리액트 앱 문제발생하여 대응 후 배포

팝업 문제 hotfix

---

src/components/common/customPopup/CustomPopup.js
src/components/common/customPopup/partials/LayerPopup.js
src/components/common/customPopup/partials/validPageDisplayOption.js

*  기획전, 상품상세 노출 기능 추가
*  전시 카테고리 세부 노출 설정 기능 추가 
*  기획전 세부 노출 설정 기능 추가 
*  상품상세 세부 노출 설정 기능 추가

[공통] 디자인 팝업 신규스팩 대응

---

src/components/Footer.js

[QA] 공통 - Footer

---

src/components/products/ViewTopContent.js

[QA] 제품 상세 > 총 상품 금액 영역 (모바일/태블릿)

---

src/components/common/SelectBox.js

[QA] 옵션 중복 선택

---

src/assets/scss/mypage.scss

[QA] 주문/목록 > 배너높이(아이패드)

---

src/App.js
src/components/Footer.js
src/components/app/AppBar.js
src/components/common/Floating.js

@nanuya Floating 버튼이랑 곂쳐서 해당부분 수정했습니다.

[앱] 앱바 : 비노출 페이지 설정 / 스크롤 인터렉션

---

src/App.js
src/components/Search.js
src/pages/footer/SearchResult.js

[QA] 검색 (/)

---

src/components/event/Bottom.js

[QA] 사이트맵 > 기획전 (탭)

---

src/App.js
src/components/Footer.js

앱에서 새창열림 잘열리는지 확인차 일부영역만 선행배포합니다.

[앱][테스트배포] 외부링크 연결시 앱 스키마 호출 : 풋터에 적용

---

published/html/footer/_terms.html
published/html/footer/terms.html
src/components/Header.js
src/hooks/support.js
src/pages/footer/terms.js

* update terms
* fix prevEnforcementDate

devstore -> release (약관)

---

src/components/Search.js
src/components/search/ResultTop.js
src/pages/footer/SearchResult.js

fix search error

---

src/components/order/Calculator.js

[QA] 마일리지 차감 된 결제금액 상이(모바일 버튼)

---

src/assets/scss/common.scss
src/components/Header.js
src/const/category.js
src/pages/esp/EspMain.js

body {
-ms-overflow-style: none;
}
body::-webkit-scrollbar {
display: none;
}
스타일 추가

[QA] 스크롤 시 Gnb 닫힘 스타일 수정

---

src/assets/scss/common.scss
src/components/Header.js
src/const/category.js

* Fix category no
* Fix esp 상품 리스트 가져올때 품절 상품도 가져오도록 수정
* fix gnb scroll style
Co-authored-by: andrea <kjkandrea@gmail.com>
Co-authored-by: choisohyun <sohyun4283@naver.com>
Co-authored-by: dj.son <dj.son@godo.co.kr>

devstore -> release (Gnb 스크롤 수정)

---

src/const/search.js
src/pages/footer/SearchResultNone.js

[QA] 검색결과없음 추천 상품 노출

---

src/components/common/Floating.js

fix floating style

---

src/components/common/Floating.js

[QA] 주문/결제

---

src/components/products/ViewTopContent.js
src/components/products/viewTopContent/Option.js
src/pages/products/ProductView.js

close #1011 
리얼 확인 필요 102265489

fix mapping option price

---

.env.development
.env.production
public/index.html
src/components/order/OrderConfirm.js
src/pages/mypage/orderDetail.js

returnUrl : 결과수신URL 이라는데 실제로 해봐야 어떤동작하는지 볼 수 있음

에스크로 구매확정 삽입 Feature/escrow pay done

---

src/components/myPage/main/OrderSummary.js

- 마이페이지에서 주문/배송 내역 검색시 넘기는 파라미터 오류 수정

마이페이지 > 주문/배송 내역 클릭시 오류 수정

---

src/pages/mypage/MyPageMember.js
src/pages/mypage/Withdraw.js

- 회원탈퇴 전 주문내역 확인 API 호출시 파라미터가 없어 해당 파라미터 추가
- 회원정보 수정 (SNS 가입회원) 추가 문구 삽입 - 25
- 회원탈퇴 (SNS 가입회원) 추가 문구 삽입 - 26

회원탈퇴 오류 수정 & SNS 회원관련 문구 추가

---

package-lock.json
package.json
public/index.html
src/components/SEO.js
src/components/SEOHelmet.js
src/const/seo.js
src/pages/Main/Main.js
src/pages/membership/Benefit.js
src/pages/support/storeInfo.js
src/pages/support/videoCourse.js

-   메타태그 관련 요청 - 69
-   react-helmet -> react-helmet-async 라이브러리 교체
-   html lang 수정
-   동영상 강좌 페이지
-   멤버십 / 등급 & 혜택 안내 페이지
-   메인페이지
-   직영점 안내 페이지
해당 페이지 정상 적용 확인 후 나머지 페이지 작업 예정입니다.

메타태그 관련 요청

---

src/assets/scss/contents.scss
src/components/event/Bottom.js
src/hooks/useTerms.js
src/pages/footer/terms.js

-  버튼이 기획전 탭의 텍스트를 가림 - 64
-  알파에서 기획전 검색시 진열이 깨짐 - 57
-  이전 이용약관 버튼 클릭 시 에러 메시지 노출 - 65
**TODO: 이용약관 링크 변경 필요**

기획전 / 이용약관 관련 작업

---

public/index.html
src/const/seo.js

- 메인페이지, 고객 서비스 : 직영점 안내, 멤버십 : 등급/혜택안내, 고객 서비스 : 동영상 강좌 타이틀 태그 추가

SEO 누락 데이터 추가

---

src/components/order/PaymentForm.js
src/const/paymentType.js
src/pages/order/OrderSheet.js

- 결제 타입 변경
- 에스크로 주문시 별도의 항목 추가

에스크로 가상계좌 -> 가상계좌 결제수단 변경

---

src/hooks/useTerms.js

이전 이용약관 페이지 이동시 조건절 제거

---

src/components/SEO.js
src/hooks/useScript.js
src/pages/Main/Main.js
src/pages/products/ProductView.js

- 스크립트 로딩과 페이지 로딩과 시간차이가 있어 useScript hooks에서 스크립트 추가할때 DOM이 load된 후 로딩되도록 변경
- SEO Component 안에  useScript hooks가 들어가 있어 SEOHelmet Component가 아닌 **SEO Component**가 적용된 페이지만 정보수집이 가능합니다. -> 정상적으로 수집되면 SEOHelmet -> SEO로 교체할 예정이니 참고 부탁드립니다.

useScript hook 수정

---

src/components/order/PaymentForm.js
src/const/paymentType.js
src/pages/order/OrderSheet.js

Reverts sokWebAdmin/sony-store-react#1098
운영 반영을 위해 잠시 원복

Revert "에스크로 가상계좌 -> 가상계좌 결제수단 변경" 원복

---

src/assets/css/common.css

- 기업구매 팝업 노출시 닫기버튼 미노출 오류 수정 - 18

기업구매 팝업 노출시 닫기버튼 미노출 오류 수정

---

src/components/SEO.js

Revert "배포를 위한 옴니추어 스크립트 제거" (재반영)

Revert "배포를 위한 옴니추어 스크립트 제거" (재반영)

---

src/assets/css/common.css
src/components/popup/PurchaseConsultingNotice.js

기업 구매 시 유의사항 팝업, 닫기 버튼 미노출  수정 (엑셀 18번)

---

src/assets/scss/common.scss
src/assets/scss/order.scss
src/components/Footer.js
src/components/myPage/orderDetail/PurchaseInfo.js
src/components/order/PaymentForm.js
src/pages/order/OrderComplete.js

공통 > 푸터
주문/결제 > 결제 방법 내 ‘가상계좌‘ 선택 시
주문/결제 > 주문 완료
마이페이지 > 주문/배송내역 > 주문 상세 조회

소비자 피해보상보험 서비스 영역 추가

---

src/components/order/PaymentForm.js
src/pages/order/OrderComplete.js

소비자 피해보상보험 서비스 영역 추가 - 텍스트 수정

---

src/assets/css/common.css
src/components/popup/PurchaseConsultingNotice.js

- `position: fixed`가 문제가 되는 부분으로 element 구조와 css 변경

기업 구매 시 유의사항 팝업, 닫기 버튼 미노출 수정

---

src/pages/mypage/Withdraw.js

- 가상계좌로  상품 구매시 회원탈퇴 가능, 배송완료가 끝나지 않은 고객 회원탈퇴 불가 처리 - 71
- 가상계좌 뿐만 아니라 입금대기 중인 주문이 있을때 회원탈퇴 불가 처리
@Geewon-Jung  현재는 최근 1년간 주문 중 입금대기 중인 주문을 찾고 있는데 기간 변경이 필요하면 꼭 확인하여 기간 변경 부탁드립니다.

입금대기 중인 주문이 있을때 회원탈퇴 불가 처리 - 71

---

src/assets/scss/esp.scss

- 전달해주신 퍼블리싱 파일에서 빠진 부분만 추가하였습니다. - 21

ESP 설명 팝업 스타일 수정 요청 - 21

---

src/assets/scss/product.scss
src/components/products/viewTopContent/Benefits.js

상품 상세 페이지 레이어 CSS 오류 수정

---

src/pages/member/Search.js

- SNS으로 가입한 계정에 대한 문구 추가(엑셀 27번)

SNS로 가입한 계정에 대한 문구 추가

---

src/assets/scss/event.scss
src/components/cart/tableParticals/ProductList.js

- 장바구니 수량 변경 오류 수정
- 기획전 리스트 커서 속성(`cursor: pointer;`) 추가

장바구니 수량 변경 오류 수정 & CSS 수정

---

src/assets/scss/event.scss
src/components/cart/tableParticals/ProductList.js

Reverts sokWebAdmin/sony-store-react#1126
장바구니 오류로 복구

Revert "장바구니 수량 변경 오류 수정 & CSS 수정"

---

src/components/cart/tableParticals/ProductList.js
src/pages/Main/Main.js
src/pages/order/Cart.js
src/utils/html.js

- 장바구니 수량 증가 / 감소 오류 수정
- 장바구니 상품 삭제 오류 수정
- 장바구니 상품 주문 오류 수정

장바구니 오류 수정

---

src/components/cart/tableParticals/ProductList.js
src/pages/Main/Main.js
src/pages/order/Cart.js
src/utils/html.js

Reverts sokWebAdmin/sony-store-react#1130

Revert "장바구니 오류 수정"

---

src/assets/scss/event.scss
src/components/cart/tableParticals/ProductList.js

Reverts sokWebAdmin/sony-store-react#1128 재반영

Revert "Revert "장바구니 수량 변경 오류 수정 & CSS 수정""

---

src/components/cart/tableParticals/ProductList.js

- escape처리때문에 & -> &amp;로 나오는 오류 수정

장바구니 상품 특수 문자 오류 처리

---

src/components/common/ViewMore.js
src/pages/event/Expired.js

- 종료된 기획전에서 기획전명 검색 오류 수정 
- 기획전 검색 후 페이징 처리가 되지 않는 문제가 있어 수정
-> 위 2가지는 애초에 개발이 잘못된 것으로 추정되며, 요청사항에 없었던 사항이니 참고 부탁드립니다

종료된 기획전에서 기획전명 검색 오류

---

src/components/products/Event.js

- 제품 상세 기획전 좌우 버튼 클릭시 동작 오류 수정

제품 상세 기획전 버튼 오류 수정

---

src/components/cart/tableParticals/TotalAmount.js
src/pages/order/Cart.js

- 장바구니에서 선택된 상품만 갯수 / 합계 보이도록 수정
- 선택된 상품이 없을 경우 0개 / 0원 노출

장바구니 합계 오류 수정

---

src/assets/scss/contents.scss
src/components/order/ShippingAddressForm.js

공백은 앞 뒤 공백만 제거해서 validation을 체크하고 있어 중간 공백은 1글자로 들어가니 참고 부탁드립니다.

주문 시 상세주소 필드 공백없이 17자 이내로 Validation check 추가

---

src/components/SEOHelmet.js

[임시 수정] 옴니츄어 테스트

---

src/components/SEOHelmet.js

Omniture dev로 임시 설정

---

src/components/SEO.js

Reverts sokWebAdmin/sony-store-react#1153

[원복] Revert "Omniture dev로 임시 설정"

---

src/components/SEOHelmet.js

[임시] 옴니츄어 테스트

---

src/assets/css/common.css
src/assets/js/ux-common.js
src/components/Footer.js
src/components/SocialLink.js
src/hooks/useClickOutside.js

- 퍼블리싱 파일을 그대로 적용했을 경우 문제가 발생해, 조금 수정하였습니다

푸터 하단의 패밀리 사이트 쪽 노출 이슈 - 5p

---

src/assets/css/common.css
src/assets/scss/common.css
src/components/order/PaymentForm.js
src/pages/error/errorServer.js

전자보증 관련 커밋

---

src/assets/css/common.css
src/assets/scss/common.css
src/components/order/PaymentForm.js
src/pages/error/errorServer.js

Reverts sokWebAdmin/sony-store-react#1171

Revert "전자보증 관련 커밋"

---

src/components/event/EventProducts.js

- 기획전에서 비회원일때도 장바구니 담기 가능하도록 수정
- 같은 상품을 장바구니에 담고 장바구니에 이동했을 경우 `구매 불가한 상품이 포함되어있어 제거 되었습니다.`라는 alert가 뜨는 부분은 이전부터 비회원 장바구니 담기 기능에 있었던 오류로 파악됩니다.

기획전에서 비회원일때도 장바구니 담기 가능하도록 수정

---

.env.development
.env.production
package.json
src/App.js
src/components/RouteChangeTracker.js

구글 GA 트래킹 추가

---

src/components/event/SectionMap.js

모바일 환경, 윈도우 사이즈 640px 미만일 경우 장바구니 담기 -> 장바구니로 문구 표시

기획전 장바구니 버튼 반응형으로 문구 수정

---

src/components/member/OpenLogin.js
src/pages/member/Callback.js

Reverts sokWebAdmin/sony-store-react#1207

Revert "Revert: SNS 로그인 작업 관련 revert"

---

src/components/member/OpenLogin.js
src/pages/member/Callback.js

Reverts sokWebAdmin/sony-store-react#1208

Revert "Revert "Revert: SNS 로그인 작업 관련 revert""

---

published/html/order/order1.html
published/html/order/order2.html
published/html/order/order3.html
published/order/order1.html
published/order/order2.html
published/order/order3.html
src/components/order/PaymentForm.js

주문 페이지 문구 수정

---

src/assets/css/common.css
src/assets/scss/common.css
src/pages/order/OrderComplete.js

SGIC 전자보증 css 및 태그 수정

---

src/components/order/PaymentForm.js

SGIC 보증보험 생년월일 alert 제거

---

src/components/common/NewSelectBox.js
src/components/order/PaymentForm.js

SGIC 보증보험 select box 수정

---

src/assets/css/common.css
src/assets/scss/order.scss

SGIC 보증보험 css 수정

---

src/pages/footer/terms.js

소니스토어 약관일자 임시 하드코딩
